'use strict';

module.exports = {
  WELCOME: 'input.welcome',
  FALLBACK: 'input.unknown',
  EXIT: 'input.exit',
  NEW_SURFACE: 'input.new_surface',
  SELECTED_OPTION: 'input.selected_option',
  DAILY_UPDATE_ASK: 'input.daily_update_ask',
  DAILY_UPDATE_SAVE: 'input.daily_update_save',
  HELP: 'input.help',
  PLANT_SAVE_IMPLICIT_TRIGGER: 'input.plant_save_implicit_trigger',
  PLANT_SAVE_IMPLICIT: 'input.plant_save_implicit',
  PLANT_SAVE_IMPLICIT_EXIT: 'input.plant_save_implicit_exit',
  PLANT_SAVE_EXPLICIT: 'input.plant_save_explicit',
  PLANT_SAVE_CONFIRM_YES: 'input.plant_save_confirm_yes',
  PLANT_SAVE_CONFIRM_NO: 'input.plant_save_confirm_no',
  PLANT_SAVE_CONFIRM_FALLBACK: 'input.plant_save_confirm_fallback',
  PLANT_SAVE: 'input.grateful_save',
  PLANT_EDIT: 'input.plant_edit',
  PLANT_SEARCH: 'input.plant_search',
  PLANT_SEARCH_IMPLICIT_TRIGGER: 'input.plant_search_implicit_trigger',
  GARDEN_CHANGE_PALETTE_YES: 'input.garden_change_palette_yes',
  GARDEN_CHANGE_PALETTE_NO: 'input.garden_change_palette_no',
  GARDEN_CHANGE_PALETTE_FALLBACK: 'fallback.garden_change_palette',
  GARDEN_CHOOSING_PALETTE_FALLBACK: 'input.garden_choosing_palette_fallback',
  GARDEN_SHOW: 'input.garden_show',
  GARDEN_SHOW_AS_LIST: 'input.garden_show_as_list',
  GARDEN_RESTART: 'input.garden_restart',
  GARDEN_RESTART_YES: 'input.garden_restart_yes',
  GARDEN_RESTART_NO: 'input.garden_restart_no',
  GARDEN_RESTART_FALLBACK: 'fallback.garden_restart',
  SXSW_PLANT_DELETE_TODAY: 'input.sxsw_plant_delete_today',
  SXSW_PLANT_IMPORT: 'input.sxsw_plant_import',
  ADMIN_USER_DELETE: 'input.admin_user_delete',
  ADMIN_USER_GET_ID: 'input.admin_user_get_id',
};
